### ISSUE TITLE
game structure / ship-placement phase

### ISSUE THREAD

**Issue by benjaminaaron** [benjaminaaron/BattleshipAI#1]
- call checkShipPlacement with row/col instead of x/y
- try to de-occupy (ships that were placed and then moved again) in garbage-collector style to avoid ghost-ships that block fields
- rotate button in addition to using the shift key for use on mobile devices without keyboard
- html-warning if js is disabled (js hides the warning on load)
- button for randomly placing ships
- use d3.min.js instead of d3.js
- supress any dragging-behaviour if !inSetupPhase
- fewer ships: 1x5, 1x4, 1x3, 2x2
- in case of invalid ship-placement-attempt: snap back to the closest possible location (horz. or vert., try sunray-style algorithm?) instead of the position before dragging started
- two fields for two player -> playfield.js logic

**Comment by benjaminaaron** [comment]
Some of these points are now obsolete since canvas is now used instead of d3. 

:+1: fewer ships
:+1: rotate button,  well, a 'rotation-switch-area' actually :smiley:
:+1: html warning
:+1: back to last valid moving position
:+1: multiple players

Remaining TODOs:
- random button
- define setup-phase with locking mechanisms
- :beetle: surprisingly canvas doesn't work out of the box on mobile, no dragging possible :confused: see if there is an easy fix

@bbuecherl Could you check if the overall structure makes sense? That would be great. It might have grown too complex and it could be done simpler code-logic wise?

**Comment by benjaminaaron** [comment]
:+1: works on mobile now :beer: 

:beetle: mouseUp event doesn't register if it happens outside of canvas, that causes inconsistent behavior when someone drags a ship outside of canvas and lets go outside

**Comment by benjaminaaron** [comment]
:+1: randomly placing ship works by pressing "r" for board0 (needs to be integrated into some kind of turn-taking management and into an UI approach)

**Comment by benjaminaaron** [comment]
:+1: buttons for done & random
:+1: turn-management
:beetle: ships can't be right next to each other: TODO

**Comment by stehrenberg** [comment]
"ships can't be right next to each other: TODO"

==> Why not? Surely, that wouldn't be the most clever move, but still - I don't see why this shouldn't be possible?

EDIT: Are we talking about...
 x x x x
......X X X X X   

or

x x x X X X X X
?

(still think both variants should be possible ^^)

**Comment by benjaminaaron** [comment]
@chanton1392 said those are the official rules and according to wikipedia he is right. So maybe it's good if we stick to the rules for the default mode? But then of course we can add switches, parameters and features to change/expand the basic rules? Let's talk about it tomorrow :smiley:

**Comment by benjaminaaron** [comment]
Closing this issue as the overall structure has changed a lot and it makes more sense to open new issues about more focused points.
