### ISSUE TITLE
investigate options for overall architecture

### ISSUE THREAD

**Issue by benjaminaaron** [benjaminaaron/BattleshipAI#2]
client, server, db
if server, node.js on server? which db?

**Comment by benjaminaaron** [comment]
### Options

**databases**
- [firebase.com](http://firebase.com) no server needed, authentication for write-access could be activated
- graph database: [neo4j.com](http://neo4j.com)
- [LevelDB](http://leveldb.org) als GraphDatabase: [nodejsconfit.levelgraph.io](http://nodejsconfit.levelgraph.io)
- [CouchDB](http://couchdb.apache.org) could be used with or without server
- just modify files on the server with node.js instead of a db

**servers**
- [digitalocean.com](http://digitalocean.com) "$100 in platform credit for new users" in the [GitHub Education package](https://education.github.com/), that'd last for 10 months on the smallest $5/month plan
- big players: [aws.amazon.com](http://aws.amazon.com), [cloud.google.com](http://cloud.google.com), [azure.microsoft.com](http://azure.microsoft.com)
- [server4you.de](http://server4you.de) (@bbuecherl has one there)
- set up (cheap) computer as own server

**server-side architectures/plugins**
- [node.js](https://nodejs.org) (use [browserify.org](http://browserify.org) to use node.js-code in the browser)
- [expressjs.com](http://expressjs.com)
- [The Lebron stack](http://lebron.technology) / [gist](https://gist.github.com/ixisio/0b3b742e4a5a40d53294)
- [socket.io](http://socket.io)

**Comment by stehrenberg** [comment]
Apart from your technology list I just created a Google Doc with what I had scribbled down as first thoughts (from last week) :)

**Comment by djung** [comment]
not sure how i got added to this project, can you remove me.  thx

**Comment by stehrenberg** [comment]
Hi djung, happened accidentally - thought you were already removed! Sorry for your trouble.

**Comment by djung** [comment]
no worries, keep on keeping on.  looks like you got some good stuff going on.

**Comment by benjaminaaron** [comment]
:smiley: Sorry @djung, it was a typo when adding you. Though I did remove you from the collaborators a second later back then and I just checked, you are not listed there. Since leaving comments on tasks is open to anyone on public repos - maybe you can "Unwatch" the repo in the top right corner to stop getting notifications?

**Comment by benjaminaaron** [comment]
_moving project and task management to external tool_
