### ISSUE TITLE
Project documents for Prof. K.

### ISSUE THREAD

**Issue by stehrenberg** [benjaminaaron/BattleshipAI#6]
Documents due on Tuesday, 2015-04-15:
- Project overview @benjaminaaron 
- Requirements @chanton1392 (?)
- Features @abstractCalculus 
- Evaluation criteria (me ^^)

**Comment by stehrenberg** [comment]
Mailed Professor Kurfess on clarification of the issues "requirements" and "evaluation criteria" and provided two examples each. Will let you know what he replies, especially the requirements will be a bit difficult to formulate (and probably be quite a bit of workload, come to think of it... ^_^°)

**Comment by stehrenberg** [comment]
Got a reply, I'm gonna start working on those documents in Google Doc and post the examples I sent him so you folks get a better grip on what's required. Please feel free to add whatever requirements you can come up with regarding our application, not sure I'll be able to think of everything :D

**Comment by benjaminaaron** [comment]
First round of documents are submitted :+1: 
Closing this task. We can reopen it for later submissions or open a new task then.
