### ISSUE TITLE
Bug Hunting - multiple hits on single field possible

### ISSUE THREAD

**Issue by stehrenberg** [benjaminaaron/BattleshipAI#7]
@djungowski found a bug playing around with the interface - it is still possible to hit a target field multiple times, it also draws multiple dots in that case.
Similar problem for target fields that contain a ship - though in this case, no additional cross is drawn.

**Comment by benjaminaaron** [comment]
Yey, a :beetle:, thanks @djungowski 
Maybe that's something for our live-coding session :smiley:

**Comment by benjaminaaron** [comment]
:+1: it's fixed now
